### ISSUE TITLE
Refactoring ToDo

### ISSUE THREAD

**Issue by splitbrain** [splitbrain/lesserphp#1]
A list of things to do for the refactoring

* [x] Run tests on github
* [x] Catch exceptions somewhere central and readd parser line numbers (use _main/colors.less for testing it)
* [x] Remove deprecated method and related properties
* [x] Check if visibility of properties and functions is correct, I think there's too much public (see a8de98a50230839a2b8e7de1371ff362ed86e71a on why that's not easy)
* [x] Check if Luma is actually Luma or if it's actually Luminosity
* [x] Clean up the tests
  * [x] InputTest
  * [x] ErrorHandling
  * [x] Api
  * [x] Server
* [x] Clean up the README and docs
* [x] Remove caching, we don't need it
* [x] fix `newFormatter()` madness
* [x] clean up all the double quotes
* [x] set up on packagist
* [x] decide on a versioning scheme
